In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()

In [13]:
from sklearn.model_selection import train_test_split
def model_score(model,data = iris):
    X_train,X_test,y_train,y_test = train_test_split(data.data,data.target,test_size = 0.4,random_state=10)
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [14]:
print('LogisticRegression',model_score(LogisticRegression(max_iter = 500)))
print('SVC',model_score(SVC()))
print('RandomForestClassifier',model_score(RandomForestClassifier()))
print('DecisionTreeClassifier',model_score(DecisionTreeClassifier()))


LogisticRegression 0.9833333333333333
SVC 0.95
RandomForestClassifier 0.9666666666666667
DecisionTreeClassifier 0.9166666666666666


In [15]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [26]:
for a,b in kf.split([11,12,13,14,15,16,17]):
    print(a,b)

[3 4 5 6] [0 1 2]
[0 1 2 5 6] [3 4]
[0 1 2 3 4] [5 6]


In [59]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits= 5)

In [60]:
def model_score2(model,a,b,c,d):
#     X_train,X_test,y_train,y_test = train_test_split(data.data,data.target,test_size = 0.4,random_state=10)
    model.fit(a,c)
    return model.score(b,d)

In [61]:
score_l = []
score_svm = []
score_rf = []
score_dt = []
digits = iris
for a,b in skf.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test = digits.data[a],digits.data[b],\
                                    digits.target[a],digits.target[b]
    
#     print(X_train[:5],y_train[:5])
    score_l.append(model_score2(LogisticRegression(max_iter=200),X_train,X_test,y_train,y_test))
    score_svm.append(model_score2(SVC(),X_train,X_test,y_train,y_test))
    score_rf.append(model_score2(RandomForestClassifier(n_estimators=50),X_train,X_test,y_train,y_test))
    score_dt.append(model_score2(DecisionTreeClassifier(),X_train,X_test,y_train,y_test))    

In [62]:
from statistics import mean
mean(score_l)

0.9733333333333334

In [63]:
mean(score_svm)

0.9666666666666667

In [64]:
mean(score_rf)

0.9666666666666667

In [65]:
mean(score_dt)

0.9666666666666667

In [67]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=200),iris.data,iris.target)

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [68]:
cross_val_score(SVC(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [69]:
cross_val_score(RandomForestClassifier(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [ ]:
cross_val_score()